# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    workingDirectory: Backend_Frontend
    displayName: 'frontend install dependencies'

- script: npm run build:staging
  workingDirectory: Backend_Frontend
  displayName: 'frontend staging build'
- task: ArchiveFiles@2
  inputs:  
    rootFolderOrFile: 'Backend_Frontend/build' 
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-staging/build.zip'
    replaceExistingArchive: true 
  displayName: 'Backend_Frontend staging zip files'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend-staging'
    ArtifactName: 'frontend-staging'
  displayName: 'Backend_Frontend staging publish to pipeline'

- script: npm run build:production
  workingDirectory: Backend_Frontend
  displayName: 'Backend_Frontend production build'
- task: ArchiveFiles@2
  inputs:  
    rootFolderOrFile: 'Backend_Frontend/build' 
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-production/build.zip'
    replaceExistingArchive: true 
  displayName: 'Backend_Frontend production zip files'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend-production'
    ArtifactName: 'frontend-production'
  displayName: 'frontend production publish to pipeline'

- script: npm run build
  workingDirectory: Backend_Frontend
  displayName: 'Backend_Frontend dev build'
- task: ArchiveFiles@2
  inputs:  
    rootFolderOrFile: 'Backend_Frontend/build' 
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-dev/build.zip'
    replaceExistingArchive: true 
  displayName: 'Backend_Frontend dev zip files'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend-dev'
    ArtifactName: 'frontend-dev'
  displayName: 'Backend_Frontend dev publish to pipeline'

